# Сводная таблица pivot_table

Сводная таблица - это мощный инструмент для обобщения и представления данных.

В Pandas для подготовки сводных таблиц вызывают метод **pivot_table()**.

Аргументы метода:

• index — ключи для группировки по индексу (строке)

• columns — ключи для группировки столбцов

• values — значения, по которым мы хотим увидеть сводную таблицу (столбцы для агрегирования)

• aggfunc — функция, применяемая к значениям (т.е. что делать с повторяющимися значениями)

<img src="https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/pic/pivot_table_pandas.png" >

Построим сводную таблицу для задачи по SEO-оптимизации.
Для начала загрузите дата-сет data.final, полученный в результате выполнения предыдущей задачи (объединения таблиц), сохраните ешл в переменной df.

In [1]:
import pandas as pd

df = pd.read_csv('data_final.csv')

print(df.head())

  subcategory_id  source  visits                subcategory_name category_id  \
0     cf2e61c7af  direct  501165              Мобильные телефоны  09f279a643
1     0cd903d1cc  direct  126342                        Ноутбуки  3509869a61
2     ef35bc88a7  direct   95626                      Телевизоры  09f279a643
3     6ff9f4014c  direct   75680                        Планшеты  3509869a61
4     72bc238e4d  direct   64435  Наушники и Bluetooth-гарнитуры  09f279a643

          category_name
0           Электроника
1  Компьютерная техника
2           Электроника
3  Компьютерная техника
4           Электроника

## Поворот данных

Создавать сводную таблицу **(pivot_table)** лучше всего последовательно. Добавляйте элементы по одному и проверяйте каждый шаг, чтобы убедиться, что вы получаете ожидаемые результаты. Самая простая сводная таблица должна иметь **DataFrame** и индекс **(index)**. 

В этом примере давайте использовать **category_name** в качестве индекса:

**pd.pivot_table(df, index=["category_name"])**

In [2]:
#pivot_table = pd.pivot_table(df, index=['category_name'])

У вас может быть несколько индексов. Фактически, большинство аргументов **pivot_table** могут принимать несколько значений в качестве элементов списка. Добавьте в список индексов переменную **subcategory_name**.

In [3]:
#pivot_table = pd.pivot_table(df, index=['category_name', 'subcategory_name'])

Вы могли заметить, что сводная таблица достаточно умна, чтобы начать агрегирование данных и их обобщение, группируя категории товаров (**category_name**) с их подкатегориями (**subcategory_name**). Теперь мы начинаем понимать, что может сделать для нас сводная таблица.

Поскольку в данном случае столбец с количественной переменной только один (**visits**), он автоматически определился в качестве значения параметра **values**. Однако, можно явно определить столбцы, которые нам нужны, с помощью этого параметра **values**:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"])**

In [4]:
# Создание сводной таблицы
pivot_table = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"])

# Вывод сводной таблицы
print(pivot_table)

                                          visits
category_name subcategory_name
Авто          Автоакустика               10674.0
              Автомагнитолы              13236.5
              Автомобильные инверторы      147.5
              Автомобильные компрессоры    598.5
              Автомобильные телевизоры    1610.5
...                                          ...
Электроника   Чехлы                       8170.0
              Чехлы-аккумуляторы           275.0
              Штативы и моноподы          1846.0
              Экшн-камеры                 8566.5
              Электронные книги           7939.5

[934 rows x 1 columns]

Столбец цен (**visits**) по умолчанию усредняет данные, но мы можем произвести подсчет количества или суммы. Добавить их можно с помощью параметра **aggfunc**:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], aggfunc='sum')**

In [5]:
# Создание сводной таблицы с суммированием значений столбца visits
pivot_table_sum = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], aggfunc='sum')

# Вывод сводной таблицы с суммированием значений
print(pivot_table_sum)

                                         visits
category_name subcategory_name
Авто          Автоакустика                21348
              Автомагнитолы               26473
              Автомобильные инверторы       295
              Автомобильные компрессоры    1197
              Автомобильные телевизоры     3221
...                                         ...
Электроника   Чехлы                       16340
              Чехлы-аккумуляторы            550
              Штативы и моноподы           3692
              Экшн-камеры                 17133
              Электронные книги           15879

[934 rows x 1 columns]

**Aggfunc** может принимать список функций.

Давайте попробуем узнать среднее значение и количество:

In [6]:
# Создание сводной таблицы с различными функциями агрегирования
pivot_table_multiple_agg = pd.pivot_table(df, 
                                          index=['category_name', 'subcategory_name'], 
                                          values=["visits"], 
                                          aggfunc=['mean', 'sum', 'count'])

# Вывод сводной таблицы с различными функциями агрегирования
print(pivot_table_multiple_agg)

                                            mean    sum  count
                                          visits visits visits
category_name subcategory_name
Авто          Автоакустика               10674.0  21348      2
              Автомагнитолы              13236.5  26473      2
              Автомобильные инверторы      147.5    295      2
              Автомобильные компрессоры    598.5   1197      2
              Автомобильные телевизоры    1610.5   3221      2
...                                          ...    ...    ...
Электроника   Чехлы                       8170.0  16340      2
              Чехлы-аккумуляторы           275.0    550      2
              Штативы и моноподы          1846.0   3692      2
              Экшн-камеры                 8566.5  17133      2
              Электронные книги           7939.5  15879      2

[934 rows x 3 columns]

Если мы хотим увидеть визиты с разбивкой по источникам трафика (**source**), переменная **columns** позволяет нам определить один или несколько столбцов.

Одна из сложностей **pivot_table** - это использование столбцов (**columns**) и значений (**values**).

Помните, что столбцы необязательны - они предоставляют дополнительный способ сегментировать актуальные значения, которые вам нужны.

Функции агрегирования применяются к перечисленным значениям (**values**):

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], columns=["source"], aggfunc='sum'])**

In [7]:
# Создание сводной таблицы с разбивкой по источникам трафика
pivot_table_source = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], columns=["source"], aggfunc='sum')

# Вывод сводной таблицы с разбивкой по источникам трафика
print(pivot_table_source)

                                        visits
source                                  direct organic
category_name subcategory_name
Авто          Автоакустика                5915   15433
              Автомагнитолы               7783   18690
              Автомобильные инверторы      145     150
              Автомобильные компрессоры    407     790
              Автомобильные телевизоры     975    2246
...                                        ...     ...
Электроника   Чехлы                       4582   11758
              Чехлы-аккумуляторы           219     331
              Штативы и моноподы          1152    2540
              Экшн-камеры                 4757   12376
              Электронные книги           4515   11364

[934 rows x 2 columns]

Теперь вы видите название категории и её подкатегории со значениями объёма трафика по каждой.

Как видно, основная категория включает в себя подкатегорию и это представлено в структуре датафрейма: категория отображена иерархически главной над подкатегорией. Такие датафреймы содержат в себе мультииндекс. Часто при работе с такими датафреймами мультииндекс убирают, чтобы категория была отображена на каждой строчке датафрейма:

**pd.pivot_table(df, index=['category_name', 'subcategory_name'], values=["visits"], 
               columns=["source"], aggfunc='sum').reset_index()**

In [8]:
# Удаление мультииндекса
pivot_table_source_reset = pivot_table_source.reset_index()

# Вывод сводной таблицы с разбивкой по источникам трафика без мультииндекса
print(pivot_table_source_reset)

       category_name           subcategory_name visits
source                                          direct organic
0               Авто               Автоакустика   5915   15433
1               Авто              Автомагнитолы   7783   18690
2               Авто    Автомобильные инверторы    145     150
3               Авто  Автомобильные компрессоры    407     790
4               Авто   Автомобильные телевизоры    975    2246
..               ...                        ...    ...     ...
929      Электроника                      Чехлы   4582   11758
930      Электроника         Чехлы-аккумуляторы    219     331
931      Электроника         Штативы и моноподы   1152    2540
932      Электроника                Экшн-камеры   4757   12376
933      Электроника          Электронные книги   4515   11364

[934 rows x 4 columns]

В таблице выше суммы визитов **visits** по каждому из источников **source (direct и organic)** представлены в отдельных столбцах. Такой вид таблицы называется «широкий». Он удобен, когда нужно сравнить значения столбцов. Хорошо заметно, например, что в подкатегории «Автомобильные инверторы» количество визитов из источников **direct** и **organic** практически одинаково, а в подкатегории «Автомагнитолы» из источника **organic** пришло почти в два раза больше посетителей, чем из **direct**.

## Расширенная фильтрация сводной таблицы

После того, как вы сгенерировали свои данные, они находятся в **DataFrame**, поэтому можно фильтровать их, используя обычные методы **DataFrame**.

Если вы хотите посмотреть только на одну категорию, например, "Товары для дома":

**data_pivot = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values='visits', columns='source',
                            aggfunc='sum').reset_index()**
**print((data_pivot[data_pivot['category_name']=='Товары для дома']).head(10))**

In [9]:
import pandas as pd

# Построение сводной таблицы
data_pivot = pd.pivot_table(df, index=['category_name', 'subcategory_name'], values='visits', columns='source', aggfunc='sum').reset_index()

# Вывод первых 10 строк для категории "Товары для дома"
print((data_pivot[data_pivot['category_name']=='Товары для дома']).head(10))

source    category_name          subcategory_name  direct  organic
646     Товары для дома                Аксессуары     219      329
647     Товары для дома    Аксессуары для готовки     216      326
648     Товары для дома        Банки для хранения     113       58
649     Товары для дома         Блюда и салатники     300      550
650     Товары для дома          Бокалы и стаканы     750     1595
651     Товары для дома                       Бра     265      452
652     Товары для дома                      Вазы     142      142
653     Товары для дома         Вешалки напольные     304      562
654     Товары для дома  Встраиваемые светильники     306      563
655     Товары для дома       Выпечка и запекание     698     1460

Или, например, мы можем узнать на какие товары запросы с органического трафика в разы больше, чем с прямого. Для этого создадим в таблице **data_pivot** новый столбец **'ratio'** и сохраните в нём значение отношения органического трафика **'organic'** к прямому **'direct'**. 

Отсортируем таблицу по столбцу 'ratio' в порядке убывания. Выведите первые 10 строк. 

**data_pivot['ratio'] = data_pivot['organic'] / data_pivot['direct']**

**data_my = data_pivot.sort_values(by = 'ratio', ascending=False)**

**print(data_my.head(10))**

In [10]:
# Добавление столбца 'ratio' и вычисление отношения organic к direct
data_pivot['ratio'] = data_pivot['organic'] / data_pivot['direct']

# Сортировка таблицы по столбцу 'ratio' в порядке убывания и вывод первых 10 строк
data_my = data_pivot.sort_values(by='ratio', ascending=False)
print(data_my.head(10))

source           category_name                    subcategory_name  direct  \
45                        Авто                                Шины   39638
105            Бытовая техника                   Стиральные машины   22064
468              Спорт и отдых                          Велосипеды   16009
205             Детские товары                             Коляски   18079
609     Строительство и ремонт                  Сварочные аппараты    6175
678            Товары для дома                 Компьютерные кресла    6208
330       Компьютерная техника                          Клавиатуры    6224
921                Электроника  Универсальные внешние аккумуляторы    6146
866                Электроника                           TV-тюнеры    6275
117            Бытовая техника                        Холодильники   20920

source  organic     ratio
45       153859  3.881604
105       64570  2.926487
468       46087  2.878818
205       52005  2.876542
609       17325  2.805668
678       17407  2.803963
330       17417  2.798361
921       17115  2.784738
866       17427  2.777211
117       57985  2.771750

# Задачи для самостоятельного выполнения

Для начала давайте представим, что мы являемся аналитиками в фирме по продаже компьютеров, программного обеспечения к ним, а также оказываем услуги по техническому сопровождению. Нам поставлена задача проанализировать участие компании в различных аукционах. 

1. Прочитайте и сохраните файл "baza.xlsx" с данными аукционов в переменную data_pd.

In [11]:
import pandas as pd

data_pd = pd.read_excel('baza.xlsx')

2. Cоздайте сводную таблицу сводную таблицу по столбцу Контрагент:

In [12]:
pivot_table_contragent = pd.pivot_table(data_pd, index=['Контрагент'], aggfunc='sum')

print(pivot_table_contragent)

                Аукцион  Количество  \
Контрагент
Альма           1002536           6
Ильин и Ко      2652638          13
Кружка и ложка  1198255          11
Микрошкин        922767          14
Шахты плюс      2265094           5

                                                         Контакт  \
Контрагент
Альма                                       Женя СидинЖеня Сидин
Ильин и Ко      Сергей ИльинСергей ИльинСергей ИльинСергей Ильин
Кружка и ложка      Виктор ЮдинВиктор ЮдинВиктор ЮдинВиктор Юдин
Микрошкин       Сергей МининСергей МининСергей МининСергей Минин
Шахты плюс               Данил СидоровДанил СидоровДанил Сидоров

                                                        Менеджер  \
Контрагент
Альма                                   Илья СергеевИлья Сергеев
Ильин и Ко      Илья СергеевИлья СергеевИлья СергеевИлья Сергеев
Кружка и ложка      Павел ПоповПавел ПоповПавел ПоповПавел Попов
Микрошкин           Павел ПоповПавел ПоповПавел ПоповПавел Попов
Шахты плюс                  Илья СергеевИлья СергеевИлья Сергеев

                                                    Продукт  \
Контрагент
Альма                           Тех. сопровождениеКомпьютер
Ильин и Ко         КомпьютерСофтТех. сопровождениеКомпьютер
Кружка и ложка  Тех. сопровождениеКомпьютерКомпьютерМонитор
Микрошкин          КомпьютерКомпьютерТех. сопровождениеСофт
Шахты плюс                           КомпьютерКомпьютерСофт

                                                         Статус    Цена
Контрагент
Альма                                         в ожиданииотменен   49000
Ильин и Ко      на рассмотрениина рассмотрениив ожиданииотменен  143100
Кружка и ложка             выигранвыигранотмененна рассмотрении  108000
Микрошкин       выигранна рассмотрениив ожиданиина рассмотрении   93100
Шахты плюс                     выигранв ожиданиина рассмотрении   44700

3. Создайте сводную таблицу по нескольким индексируемым столбцам  'Контакт', 'Менеджер':

In [13]:
pivot_table_contact_manager = pd.pivot_table(data_pd, index=['Контакт', 'Менеджер'], aggfunc='sum')

print(pivot_table_contact_manager)

                            Аукцион  Количество  \
Контакт       Менеджер
Виктор Юдин   Павел Попов   1198255          11
Данил Сидоров Илья Сергеев  2265094           5
Женя Сидин    Илья Сергеев  1002536           6
Сергей Ильин  Илья Сергеев  2652638          13
Сергей Минин  Павел Попов    922767          14

                                                                   Контрагент  \
Контакт       Менеджер
Виктор Юдин   Павел Попов   Кружка и ложкаКружка и ложкаКружка и ложкаКруж...
Данил Сидоров Илья Сергеев                     Шахты плюсШахты плюсШахты плюс
Женя Сидин    Илья Сергеев                                         АльмаАльма
Сергей Ильин  Илья Сергеев           Ильин и КоИльин и КоИльин и КоИльин и Ко
Сергей Минин  Павел Попов                МикрошкинМикрошкинМикрошкинМикрошкин

                                                                Продукт  \
Контакт       Менеджер
Виктор Юдин   Павел Попов   Тех. сопровождениеКомпьютерКомпьютерМонитор
Данил Сидоров Илья Сергеев                       КомпьютерКомпьютерСофт
Женя Сидин    Илья Сергеев                  Тех. сопровождениеКомпьютер
Сергей Ильин  Илья Сергеев     КомпьютерСофтТех. сопровождениеКомпьютер
Сергей Минин  Павел Попов      КомпьютерКомпьютерТех. сопровождениеСофт

                                                                     Статус  \
Контакт       Менеджер
Виктор Юдин   Павел Попов              выигранвыигранотмененна рассмотрении
Данил Сидоров Илья Сергеев                 выигранв ожиданиина рассмотрении
Женя Сидин    Илья Сергеев                                в ожиданииотменен
Сергей Ильин  Илья Сергеев  на рассмотрениина рассмотрениив ожиданииотменен
Сергей Минин  Павел Попов   выигранна рассмотрениив ожиданиина рассмотрении

                              Цена
Контакт       Менеджер
Виктор Юдин   Павел Попов   108000
Данил Сидоров Илья Сергеев   44700
Женя Сидин    Илья Сергеев   49000
Сергей Ильин  Илья Сергеев  143100
Сергей Минин  Павел Попов    93100

4. По умолчанию сводная таблица выводится по всем числовым полям, однако это не всегда удобно, а иногда и лишено смысла, поэтому можно выводить сводные данные только по отдельным столбцам. Выведите только столбец "Стоимость", для этого добавьте параметр values=['Цена']:

In [14]:
pivot_table_price = pd.pivot_table(data_pd, index=['Контрагент'], values=['Цена'])

print(pivot_table_price)

                   Цена
Контрагент
Альма           24500.0
Ильин и Ко      35775.0
Кружка и ложка  27000.0
Микрошкин       23275.0
Шахты плюс      14900.0

5. Столбец с ценой по умолчанию выводит среднее значение, однако нам скорее интересна сумма продаж. Добавляем параметр aggfunc='sum':

In [15]:
pivot_table_price_sum = pd.pivot_table(data_pd, index=['Контрагент'], values=['Цена'], aggfunc='sum')

print(pivot_table_price_sum)

                  Цена
Контрагент
Альма            49000
Ильин и Ко      143100
Кружка и ложка  108000
Микрошкин        93100
Шахты плюс       44700

6. С помощью параметра columns выведите в столбцы наименование продуктов:

In [16]:
pivot_table_product = pd.pivot_table(data_pd, index=['Контрагент'], values=['Цена'], columns=['Продукт'])

print(pivot_table_product)

                    Цена
Продукт        Компьютер Монитор     Софт Тех. сопровождение
Контрагент
Альма            42000.0     NaN      NaN             7000.0
Ильин и Ко       42150.0     NaN  37600.0            21200.0
Кружка и ложка   41950.0  9300.0      NaN            14800.0
Микрошкин        21950.0     NaN  46900.0             2300.0
Шахты плюс       19000.0     NaN   6700.0                NaN

7. Наверное вы обратили внимание, что в ячейках, где нет данных пусто, хотя нам привычнее, что бы в таких полях указывалось бы значение 0. Добавьте параметр fill_value=0:

In [17]:
pivot_table_product = pd.pivot_table(data_pd, index=['Контрагент'], values=['Цена'], columns=['Продукт'], fill_value=0)

print(pivot_table_product)

                    Цена
Продукт        Компьютер Монитор     Софт Тех. сопровождение
Контрагент
Альма            42000.0     0.0      0.0             7000.0
Ильин и Ко       42150.0     0.0  37600.0            21200.0
Кружка и ложка   41950.0  9300.0      0.0            14800.0
Микрошкин        21950.0     0.0  46900.0             2300.0
Шахты плюс       19000.0     0.0   6700.0                0.0

8. Вероятно полезно было бы рассматривать эффективность деятельности наших менеджеров не только по стоимости продаж, но и по их количеству. Добавьте в параметр values переменную  "Количество"

In [18]:
pivot_table_price_quantity = pd.pivot_table(data_pd, index=['Контрагент'], values=['Цена', 'Количество'], aggfunc='sum')

print(pivot_table_price_quantity)

                Количество    Цена
Контрагент
Альма                    6   49000
Ильин и Ко              13  143100
Кружка и ложка          11  108000
Микрошкин               14   93100
Шахты плюс               5   44700

9. Выведите продажи только менеджера "Илья Сергеев":

In [19]:
pivot_table_ilya = pd.pivot_table(data_pd[data_pd['Менеджер'] == 'Илья Сергеев'], index=['Контрагент'], values=['Цена'], aggfunc='sum')

print(pivot_table_ilya)

              Цена
Контрагент
Альма        49000
Ильин и Ко  143100
Шахты плюс   44700